BEGIN;

DROP TABLE IF EXISTS 
"user",
"book",
"library",
"library_book",
"genre",
"genre_book",
"review";


CREATE TABLE "user" (
 "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 "name" VARCHAR(100) NOT NULL,
 "firstname" VARCHAR(100) NOT NULL,
 "email" VARCHAR(100) NOT NULL UNIQUE,
 "password" TEXT NOT NULL,
 "admin" BOOLEAN NOT NULL DEFAULT false,
 "createdAt" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
 "updatedAt" timestamptz
);


CREATE TABLE "library" (
 "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 "name" VARCHAR(100) NOT NULL,
 "user_id" integer NOT NULL REFERENCES "user"("id"),
 "createdAt" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
 "updatedAt" timestamptz
);


CREATE TABLE "genre" (
 "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 "name" VARCHAR(100) NOT NULL UNIQUE
);


CREATE TABLE "book" (
 "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 "isbn" VARCHAR(100) NOT NULL UNIQUE,
 "title" VARCHAR(500) NOT NULL,
 "author" VARCHAR(100) NOT NULL,
 "summary" TEXT NOT NULL,
 "image" VARCHAR(500) NOT NULL,
 "pages" integer,
 "editor" VARCHAR(100),
 "publication_year" integer
);


CREATE TABLE "library_book" (
 "library_id" integer NOT NULL REFERENCES "library"("id"),
 "book_id" integer NOT NULL REFERENCES "book"("id"),
 "read" BOOLEAN NOT NULL DEFAULT false,
 "createdAt" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
 "updatedAt" timestamptz,
 UNIQUE ("library_id", "book_id")
);


CREATE TABLE "genre_book" (
 "genre_id" integer NOT NULL REFERENCES "genre"("id"),
 "book_id" integer NOT NULL REFERENCES "book"("id"),
 UNIQUE ("genre_id", "book_id")
);

CREATE TABLE "review" (
 "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 "content" TEXT NOT NULL,
 "rating" INTEGER CHECK ("rating" BETWEEN 1 AND 5),
 "user_id" integer NOT NULL REFERENCES "user"("id") ON DELETE CASCADE,
 "book_id" integer NOT NULL REFERENCES "book"("id") ON DELETE CASCADE,
 "createdAt" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
 "updatedAt" timestamptz,
 UNIQUE ("user_id", "book_id")
);


COMMIT;
